config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :categories do
    resources :entries#, only: [:new, :create]
  end
  resources :example_categories, controller: 'categories', type: 'ExampleCategory' do
    resources :entries
  end
  resources :getting_started_categories, controller: 'categories', type: 'GettingStartedCategory' do
    resources :entries
  end

	root 'welcome#index'
	resources :entries#, except: [:new, :create]
	devise_for :users, skip: [:registrations]

  get 'getting_started' => 'categories#getting_started', as: 'getting_started'
  get 'examples' => 'categories#examples', as: 'examples'

	# get 'entries/:id/data/:name' => 'entries#data'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :entries

  has_attached_file :thumbnail, styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/
end

app/models/datum.rb
class Datum < ActiveRecord::Base
	belongs_to :entry
end

app/models/embedded_widget.rb
class EmbeddedWidget < Widget; end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :category

	has_many :datum
  accepts_nested_attributes_for :datum, :reject_if => :all_blank, :allow_destroy => true

	has_many :widgets, -> { order(:index) }
	accepts_nested_attributes_for :widgets, :reject_if => :all_blank, :allow_destroy => true

  has_attached_file :thumbnail, styles: { small: "200x200" }
  validates_attachment_content_type :thumbnail, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/example_category.rb
class ExampleCategory < Category; end

app/models/general_widget.rb
class GeneralWidget < Widget; end

app/models/getting_started_category.rb
class GettingStartedCategory < Category; end

app/models/iframe_widget.rb
class IframeWidget < Widget; end

app/models/image_widget.rb
class ImageWidget < Widget; end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  belongs_to :entry

  has_attached_file :image, styles: { small: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  default_scope { order(order: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  # before_action :set_categories, only: [:index, :show, :recently_updated, :recently_created]
  before_action :authenticate_user!, except: [:examples, :getting_started]

  respond_to :html

  def examples
    @categories = ExampleCategory.all
  end

  def getting_started
    @categories = GettingStartedCategory.all
  end
  #
  # def index
  #   respond_with(@categories)
  # end
  #
  # def show
  #   @entries = @category.entries.order("updated_at DESC")
  #   respond_with(@category)
  # end

  # def recently_updated
  #   @entries = Entry.all.order("updated_at DESC")
  #   render :show
  # end
  #
  # def recently_created
  #   @entries = Entry.all.order("created_at DESC")
  #   render :show
  # end

  def new
    @category = Category.new(type: params[:type])
    respond_to :js
  end

  def edit
    respond_to :js
  end

  def create
    @category = Category.new(type: params[:type])
    @category.update(category_params)
    redirect_to :back
  end

  def update
    @category.update(category_params)
    redirect_to :back
  end

  def destroy
    @category.destroy
    redirect_to :back
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(params[:type].underscore.to_sym).permit(:name, :thumbnail, :fa_icon)#, :entry_ids => [])
    end

    # def set_categories
    #   @categories = Category.all.order("name")
    # end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_action :set_entry, only: [:show, :edit, :update, :destroy, :data, :data_form]
	before_action :set_category, only: [:new, :edit, :show, :update, :create]
	before_action :authenticate_user!, except: [:show]
	respond_to :html

	# GET /entries
	# GET /entries.json
	# def index
	# 	if user_signed_in?
	# 		@entries = Entry.all
	# 	else
	# 		@entries = Entry.select {|x| x.private == false}.reverse
	# 	end
	# 	@entries = @entries.sort_by{|entry| entry.updated_at }
	# end


	# GET /entries/1
	# GET /entries/1.json
	def show
		# authenticate_user! if(@entry.private)
		@widgets = @entry.widgets.sort_by{|widget| widget.index }
	end

	# def data
	# 	authenticate_user! if(@entry.private)
	# 	@data = @entry.datum.find {|x| x.name == params[:name]}
	# 	render plain: @data.body
	# end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = @category.entries.create(entry_params)
		show_it
  end

  def update
    @entry.update(entry_params)
		show_it
  end

  def destroy
    @entry.destroy
    redirect_to :back
  end


	private
		# Use callbacks to share common setup or constraints between actions.
		def set_entry
			@entry = Entry.find(params[:id])
		end
		def set_category
			@category = Category.find(
				params[:category_id] ||
				params[:example_category_id] ||
				params[:getting_started_category_id]
			)
		end

		def entry_params
			params.require(:entry).permit(
				:name, :description, :markdown,
				widgets_attributes: [:id, :name, :order, :caption, :css, :html, :js, :markdown, :code_visibility, :_destroy]
			)
		end

		def show_it
			if @category.type == "ExampleCategory"
				redirect_to [@category, @entry]
			elsif @category.type == "GettingStartedCategory"
				redirect_to getting_started_path
			else
				redirect_to root_url
			end
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		# def entry_params
		# 	params.require(:entry).permit(
		# 		:name, :description, :thumbnail, :code, :private, :markdown, :iframe, :category_ids => [],
		# 		widgets_attributes: [:id, :index, :name, :caption, :type, :iframe_url, :embedded_code, :image, :markdown, :_destroy],
		# 		datum_attributes: [:id, :name, :body, :_destroy]
		# 	)
		# end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
require 'github/markup'

module EntriesHelper

	def markup text
		text ||= ''
		GitHub::Markup.render('README.markdown', text).html_safe
	end

	# def markdown(text)
	# 	options = {
	# 		filter_html:     true,
	# 		hard_wrap:       true,
	# 		link_attributes: { rel: 'nofollow', target: "_blank" },
	# 		space_after_headers: true,
	# 		fenced_code_blocks: true
	# 	}

	# 	extensions = {
	# 		autolink:           true,
	# 		superscript:        true,
	# 		disable_indented_code_blocks: true
	# 	}

	# 	renderer = Redcarpet::Render::HTML.new(options)
	# 	markdown = Redcarpet::Markdown.new(renderer, extensions)

	# 	markdown.render(text).html_safe
	# end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: { multipart: true }) do |f| %>
  <!-- <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> -->

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "name-input" %>
  </div>

  <div class="field">
    <%= f.label :fa_icon, "Font Awesome Icon" %><br>
    <%= f.text_field :fa_icon%>
  </div>

  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.file_field :thumbnail %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/edit.js.erb
_app.modalContent = '<%=j render  "form" %>';
_app.modal();

app/views/categories/examples.html.erb
<div id = "examples">

  <div class = "container" id = "page-header">
    <h1>Examples</h1>
    <p>
      Here is a list of examples using many of d2b's charts and utilities.
    </p>
  </div>

  <div class = "categories">
    <% @categories.sort_by(&:name).each do |category| %>
      <div class = "category-header">
        <% unless category.fa_icon.blank? %>
          <i class = "fa-background fa fa-<%= category.fa_icon %>"></i>
        <% else %>
          <div class = "background" style="background-image:url('<%= category.thumbnail.url %>')"></div>
        <% end %>

        <h2 class = "container"  >
          <%= category.name %>
        </h2>

        <% if user_signed_in? %>
          <div class = "category-options">
            <%= link_to "Edit", edit_category_path(category), class: "link", remote: true %> |
            <%= link_to "Destroy", category, method: :delete, data: { confirm: "Are you sure?" }, class: "link" %>
          </div>
        <% end %>
      </div>
      <div class = "container category">
        <% category.entries.sort_by(&:name).each do |entry| %>
          <div class = "entry">
            <h3><%= link_to entry.name, [category, entry], class: "link" %></h3>
            <p>
              <%= entry.description %>
            </p>

            <% if user_signed_in? %>
              <%= link_to "Edit", edit_category_entry_path(category, entry), class: "link" %> |
              <%= link_to "Destroy", entry, method: :delete, data: { confirm: "Are you sure?" }, class: "link" %>
            <% end %>
          </div>
        <% end %>

        <% if user_signed_in? %>
          <div class = "entry">
            <%= link_to new_category_entry_path(category) do %>
              <h3 class = "link new-entry-button">New Entry +</h3>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to new_example_category_path, remote: true do %>
        <div class = "category-header new-category-button">
            <h2 class="container">New Category +</h2>
        </div>
      <% end %>
    <% end %>

  </div>

</div>

app/views/categories/getting_started.html.erb
<div id = "getting-started">

  <div class = "container" id = "page-header">
    <h1>Getting Started</h1>
    <p>
      Here we will go over a few steps that will help you get started using d2b.
    </p>
  </div>

  <div class = "categories">

    <% @categories.each do |category| %>
      <div class = "category-header">
        <% unless category.fa_icon.blank? %>
          <div class = "fa-background"><i class="fa fa-<%= category.fa_icon %>"></i></div>
        <% else %>
          <div class = "background" style="background-image:url('<%= category.thumbnail.url(:small) %>')"></div>
        <% end %>

        <h2 class = "container"  >
          <%= category.name %>
        </h2>

        <% if user_signed_in? %>
          <div class = "category-options">
            <%= link_to "Edit", edit_category_path(category), class: "link", remote: true %> |
            <%= link_to "Destroy", category, method: :delete, data: { confirm: "Are you sure?" }, class: "link" %>
          </div>
        <% end %>
      </div>

      <div class="entries">
        <% category.entries.each do |entry| %>

          <div class="entry">

            <div class = "entry-content container">
              <%= content_tag :h2, entry.name if !entry.name.to_s.empty? %>

              <% if user_signed_in? %>
                <div class = "entry-links">
                  <%= link_to "Edit", edit_category_entry_path(category, entry), class: "link" %> |
                  <%= link_to "Destroy", entry, method: :delete, data: { confirm: "Are you sure?" }, class: "link" %>
                </div>
              <% end %>

              <p>
                <%= entry.description %>
              </p>

              <%= content_tag :div,
                              markup(entry.markdown),
                              class: "markdown-body" unless entry.markdown.to_s.empty?
                              %>
            </div>

            <% if entry.widgets.length > 0 %>
              <ol class="widgets">
                <% entry.widgets.each do |widget| %>
                  <%= render "widgets/show", :widget => widget %>
                <% end %>
              </ol>
            <% end %>

          </div>

        <% end %>
      </div>

      <% if user_signed_in? %>
        <div class = "entry container">
          <%= link_to new_category_entry_path(category) do %>
            <h3 class = "link new-entry-button">New Entry +</h3>
          <% end %>
        </div>
      <% end %>
    <% end %>


    <% if user_signed_in? %>
      <%= link_to new_getting_started_category_path, remote: true do %>
        <div class = "category-header new-category-button">
            <h2 class="container">New Category +</h2>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/new.js.erb
_app.modalContent = '<%=j render  "form" %>';
_app.modal();

app/views/categories/show.html.erb
<div id="category-nav">
  <%= link_to "Recently Updated",
              recently_updated_path,
              class:'category-nav-cell category-nav-item',
              data:{current:current_page?(recently_updated_path) || current_page?(root_url)}
  %>
  <%= link_to "Recently Created",
              recently_created_path,
              class:'category-nav-cell category-nav-item',
              data:{current:current_page?(recently_created_path)}
  %>
  <li class="category-menu category-nav-cell">
    <%= link_to @category, class: "category-nav-item", data:{current:!!@category} do %>
      <%= (@category)? @category.name : "Category" %> <i class="fa fa-caret-down"></i>
    <% end %>
    <ul class="submenu">
      <% @categories.each do |category| %>
          <li class="hover-menu">
            <%= category.name %>
        		<% if user_signed_in? %>
        			<div class="links">
          			<%= link_to "EDIT", edit_category_path(category) %>
          			<%= link_to "DESTROY", category, method: :delete, data: { confirm: "Are you sure?" } %>
        			</div>
        		<% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </li>
</div>

app/views/entries/_form.html.erb
<%= form_for([@category, @entry]) do |f| %>
  <!-- <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> -->

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "name-input" %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :markdown %><br>
    <%= f.text_area :markdown %>
  </div>

  <div class="widgets">
    <%= f.fields_for :widgets do |widget| %>
      <%= render 'widget_fields', f: widget %>
    <% end %>
    <div class="links">
      <%= link_to_add_association(
            'Add Widget +',
            f,
            :widgets,
            class: "link",
            data: {association_insertion_method: "before"}
          )
      %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/entries/_index.html.erb
<% @entries.each do |entry| %>
	<% next if entry.private && !user_signed_in? %>
	<div class="entry">
		<%= link_to entry do %>
			<h2><%= entry.name %></h2>
			<p><i><%= entry.description %></i></p>
			<% if entry.thumbnail.exists? %>
				<div class="thumbnail">
					<%= image_tag entry.thumbnail.url %>
				</div>
			<% end %>
			<span>
				Updated: <%= entry.updated_at.strftime("%b %d %Y") %> &mdash; Created: <%= entry.created_at.strftime("%b %d %Y") %>
			</span>
		<% end %>
	</div>
<% end %>

app/views/entries/_widget_fields.html.erb
<div class="edit-widget widget container nested-fields">
  <%= link_to_remove_association f do %>
    <div class="close-button"></div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name-input2"%>
  </div>
  <div class="field">
    <%= f.label :order %>
    <%= f.text_field :order %>
  </div>
  <div class="field">
    <%= f.label :markdown %>
    <%= f.text_area :markdown %>
  </div>
  <div class="field">
    Default Code Selection -
    <%= f.radio_button :code_visibility, "js", class: "code-visibility-value" %>
    <%= f.label :code_visibility, "JavaScript", :value => "js"  %>
    <%= f.radio_button :code_visibility, "html", class: "code-visibility-value" %>
    <%= f.label :code_visibility, "HTML", :value => "html"  %>
    <%= f.radio_button :code_visibility, "css", class: "code-visibility-value" %>
    <%= f.label :code_visibility, "CSS", :value => "css"  %>
    <%= f.radio_button :code_visibility, "none", class: "code-visibility-value" %>
    <%= f.label :code_visibility, "None", :value => "none"  %>
  </div>

  <%= f.hidden_field :js, class: "js-hidden-value" %>
  <%= f.hidden_field :html, class: "html-hidden-value" %>
  <%= f.hidden_field :css, class: "css-hidden-value" %>

  <%= render 'widgets/embedded_components' %>
</div>

app/views/entries/edit.html.erb
<div class = "container" id = "page-header">
  <h1>Editing Entry</h1>
  <p>for <%= @category.name %></p>
</div>
<div class = "container">
  <%= render 'form' %>
</div>

app/views/entries/new.html.erb
<div class = "container" id = "page-header">
  <h1>Creating Entry</h1>
  <p>for <%= @category.name %></p>
</div>
<div class = "container">
  <%= render 'form' %>
</div>

app/views/entries/show.html.erb
<div class = "entry">

  <div class = "container" id = "page-header">
    <h1><%= @entry.name %></h1>
    <% unless @entry.description.blank? %>
      <p>
        <%= @entry.description %>
      </p>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class = "entry-links container">
      <%= link_to "Edit", edit_category_entry_path(@category, @entry), class: "link" %>
      <!-- |
      <%= link_to "Destroy", @entry, method: :delete, data: { confirm: "Are you sure?" }, class: "link" %> -->
    </div>
  <% end %>

  <%= content_tag :div,
                  markup(@entry.markdown),
                  class: "markdown-body container" unless @entry.markdown.to_s.empty?
                  %>

  <ol class="widgets">
    <% @entry.widgets.each do |widget| %>
      <%= render "widgets/show", :widget => widget %>
    <% end %>
  </ol>

</div>

app/views/layouts/_modal.html.erb
<div class="modal">
  <input class="modal-state" id="modal-1" type="checkbox"/>
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <div class="modal-close close-button" for="modal-1"></div>
      <div class="modal-content"></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <% if Rails.env.production? %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111208921-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-111208921-1');
    </script>
  <% end %>


  <title>D2B.js | Data to DashBoards</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='//fonts.googleapis.com/css?family=Lato:300,400,700,300italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <span id="logo"><%= link_to "/" do %> d2b.js | Data to DashBoards <% end %></span>
    <i class="fa fa-bars nav-open"></i>
    <nav>
      <%= link_to "Getting Started", getting_started_path %>
      <%= link_to "Examples", examples_path %>
      <%= link_to "Wiki", "http://docs.d2bjs.org", target: "_blank" %>
      <%= link_to "Source", "//github.com/d2bjs/d2b", target: "_blank" %>
      <!-- <%= link_to "Sign In", "/users/sign_in" if !user_signed_in?%> -->
      <%= link_to "Sign Out", "/users/sign_out", method: :delete if user_signed_in?%>
    </nav>
  </header>

  <div class = 'github-buttons'>
    <!-- Place this tag where you want the button to render. -->
    <a class="github-button" href="https://github.com/d2bjs/d2b" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star d2bjs/d2b on GitHub">Star</a>
  </div>

  <div id="main">
    <%= yield %>
  </div>

  <!-- <footer class="container">
  </footer> -->

  <%= render 'layouts/modal' %>

  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>

app/views/welcome/index.html.erb
<div id = "welcome">

  <div class = "container" id = "page-header">
    <%= image_tag 'logo.png', class: 'd2b-logo' %>
    <p>
      D2B is a reusable charting library that uses the data visualization library D3.js. D2B is packed full of features for various types of charts. It also includes hooks to customize each chart to fit your needs. Take a look at the demos below to get an idea of what D2B can do.
    </p>
  </div>

  <axis-chart-demo></axis-chart-demo>
  <sunburst-chart-demo></sunburst-chart-demo>
  <pie-chart-demo></pie-chart-demo>

</div>

<script>
  (function () {

    var welcome = new Vue({
      el: "#welcome",
      data: {
      }
    });

  })();
</script>

app/views/widgets/_embedded_components.html.erb
<iframe scrolling="no" class="iframe-chart"></iframe>

<div class="code-wrapper">
  <div class="code-buttons">
    <div class="js-button" data-type="js">JS</div>
    <div class="html-button" data-type="html">HTML</div>
    <div class="css-button" data-type="css">CSS</div>
  </div>
  <div class="code-container js-container">
    <div class="error js-error"></div>
    <div class="code js-editor"></div>
  </div>
  <div class="code-container html-container">
    <div class="error html-error"></div>
    <div class="code html-editor"></div>
  </div>
  <div class="code-container css-container">
    <div class="error css-error"></div>
    <div class="code css-editor"></div>
  </div>
</div>

<script>
  (function(){ <%= render 'widgets/setup_editors.js' %> })();
</script>

app/views/widgets/_embedded_widget.html.erb
<%= hidden_field_tag 'js', widget.js, class: "js-hidden-value" %>
<%= hidden_field_tag 'html', widget.html, class: "html-hidden-value" %>
<%= hidden_field_tag 'css', widget.css, class: "css-hidden-value" %>
<%= hidden_field_tag 'code_visibility', widget.code_visibility, class: "code-visibility-value" %>

<%= render 'widgets/embedded_components' %>

app/views/widgets/_iframe_widget.html.erb
<%= content_tag :iframe, nil, src: widget.iframe_url, class: "widget-iframe" %>
<%= link_to "Open in a new window.", widget.iframe_url, target: "_blank", class:"iframe-link" %>

app/views/widgets/_image_widget.html.erb
<%= image_tag("#{widget.image.url}") %>

app/views/widgets/_show.html.erb
<div class="widget container" id="widget-<%= widget.id %>">
  <%= content_tag :li, widget.name, class: "widget-name" if !widget.name.to_s.empty? %>
  <br>
  <div class="markdown-body"><%= markup(widget.markdown) %></div>
  <%= render "widgets/#{widget.type.underscore}", :widget => widget %>
  <div class="widget-caption"><%= widget.caption %></div>
</div>